date-table not fixed
probably this components props not include setList props.
error: Type '{ list: { test: string; }[]; setList: (list: any) => void; listColumnKey: string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'setList' does not exist on type 'IntrinsicAttributes & Props'.